import React, { useState } from 'react';
import { useRaven } from '../context/RavenContext';
import TrustBadge from '../components/common/TrustBadge';
import { 
  FileText, 
  Copy, 
  Download, 
  CheckCircle, 
  Send, 
  Building2, 
  MapPin, 
  Lock
} from 'lucide-react';

export default function AdminPage() {
  const { 
    profile, 
    civicClusters, 
    civicReports, 
    updateClusterStatus, 
    addOfficialResponse, 
    markGrievanceSubmitted,
    navigateTo 
  } = useRaven();

  // Call all hooks unconditionally at the top of the component
  const [selectedClusterId, setSelectedClusterId] = useState(civicClusters[0]?.id || 'CI-1024');
  const [copied, setCopied] = useState(false);
  const [officialResponseText, setOfficialResponseText] = useState('');
  const [responseSuccess, setResponseSuccess] = useState(false);

  // Role Protection: Guard against non-admin access
  if (profile.role !== 'Admin') {
    return (
      <div className="max-w-2xl mx-auto px-4 py-16 text-center space-y-4">
        <div className="w-12 h-12 rounded-full bg-rose-100 text-rose-700 flex items-center justify-center mx-auto">
          <Lock className="w-6 h-6" />
        </div>
        <h1 className="text-xl font-bold text-slate-900">Admin Access Restricted</h1>
        <p className="text-xs text-slate-600 leading-relaxed max-w-md mx-auto">
          This administration and collective grievance generation console is only accessible to accounts with the <strong>Admin</strong> demo role.
        </p>
        <div className="pt-2">
          <button
            onClick={() => navigateTo('profile')}
            className="px-4 py-2 bg-slate-900 text-white rounded text-xs font-semibold hover:bg-slate-800 transition"
          >
            Switch to Admin Role in Profile
          </button>
        </div>
      </div>
    );
  }

  const selectedCluster = civicClusters.find(c => c.id === selectedClusterId) || civicClusters[0];
  const clusteredReports = civicReports.filter(r => r.clusterId === selectedCluster?.id);

  // Generate Collective Grievance Text
  const generateCollectiveGrievanceText = (cluster) => {
    if (!cluster) return '';

    return `================================================================================
COLLECTIVE CITIZEN GRIEVANCE PETITION — CORROBORATED GROUND EVIDENCE
================================================================================
Generated by: RAVEN Civic Intelligence Platform (Tamil Nadu Region)
Record Classification: Collective Citizen Corroboration (Non-Official Civic Submission)
Date Generated: ${new Date().toLocaleDateString('en-IN', { dateStyle: 'full' })}
Platform Tracking ID: ${cluster.id}

1. TARGET CIVIC ENTITY / JURISDICTION:
   Department / Agency: ${cluster.department}
   District / Administrative Region: ${cluster.district}
   Correlated Location: ${cluster.location}
   Specific Affected Streets: ${(cluster.affectedLocations || []).join(', ')}

2. CIVIC ISSUE SUMMARY & SEVERITY:
   Issue Category: ${cluster.category}
   Issue Subject: ${cluster.title}
   Assessed Severity: ${cluster.severity}
   Duration Observed: ${cluster.durationDays} days continuously unaddressed
   Deterministic AI-Assisted Priority Score: ${cluster.aiPriorityData?.score || 84} / 100
   Public Support Score (Citizen Upvotes): ${cluster.publicSupportScore} / 100

3. SYNTHESIZED GROUND CORROBORATION:
   "${cluster.aiSummary}"

4. AGGREGATED CITIZEN EVIDENCE & SAMPLE STATEMENTS:
   Total Citizen Submissions in Cluster: ${cluster.reportsCount}
   Community Confirmations: ${cluster.confirmationsCount}
   Attached Ground Evidence Count: ${cluster.evidenceCount} citizen-provided files

   Excerpts from Ground Submissions (All submitters anonymous for public privacy):
${clusteredReports.slice(0, 4).map((r, i) => `   [${i + 1}] (${r.location} • ${r.date}): "${r.text}"`).join('\n')}

5. FORMAL COMMUNITY PRAYER / SUBMISSION:
   Residents of the aforementioned area respectfully petition ${cluster.department}
   to inspect the reported defect, initiate corrective maintenance, and issue an official status update.

SUBMISSION PROTOCOL:
Status: Prepared for Official Submission
Submission Mode: Manually Submitted by RAVEN Admin via Public Grievance Portal (${cluster.relevantOfficialChannels?.portal || 'https://gccservices.chennaicorporation.gov.in/pgr'})
================================================================================`;
  };

  const grievanceContent = generateCollectiveGrievanceText(selectedCluster);

  const handleCopyGrievance = () => {
    navigator.clipboard.writeText(grievanceContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadGrievance = () => {
    const blob = new Blob([grievanceContent], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `RAVEN-Collective-Grievance-${selectedCluster.id}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleStatusChange = (newStatus) => {
    updateClusterStatus(selectedCluster.id, newStatus);
  };

  const handleMarkSubmitted = () => {
    markGrievanceSubmitted(selectedCluster.id);
  };

  const handleAddResponse = (e) => {
    e.preventDefault();
    if (!officialResponseText.trim()) return;
    addOfficialResponse(selectedCluster.id, officialResponseText.trim());
    setOfficialResponseText('');
    setResponseSuccess(true);
    setTimeout(() => setResponseSuccess(false), 3000);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
      {/* Page Header */}
      <div className="flex flex-wrap items-start justify-between gap-4 pb-6 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xs font-bold uppercase tracking-wider text-amber-600 bg-amber-50 px-2 py-0.5 rounded border border-amber-200">
              Admin Console
            </span>
            <span>•</span>
            <span className="text-xs font-semibold text-slate-500">
              Escalation & Collective Grievance Dispatch
            </span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 tracking-tight">
            Escalation Queue & Collective Grievances
          </h1>
          <p className="text-xs text-slate-600 mt-1 leading-relaxed max-w-3xl">
            Review high-impact civic clusters, inspect aggregated citizen evidence, generate formal collective grievance petitions, and log official responses. No direct government API required; grievances are prepared for manual submission by administrator.
          </p>
        </div>

        <div className="flex items-center gap-2">
          <span className="text-xs px-3 py-1.5 rounded-lg bg-amber-100 text-amber-900 font-semibold border border-amber-200">
            Role: {profile.name}
          </span>
        </div>
      </div>

      {/* Main Grid: Left = Queue, Right = Grievance Petition Generator */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Escalation Queue List (4 cols) */}
        <div className="lg:col-span-4 space-y-3">
          <div className="flex items-center justify-between pb-1">
            <h2 className="text-xs font-bold uppercase tracking-wider text-slate-800">
              Monitored Civic Clusters ({civicClusters.length})
            </h2>
            <span className="text-[11px] text-slate-400">Select to manage</span>
          </div>

          <div className="space-y-2.5 max-h-[700px] overflow-y-auto pr-1">
            {civicClusters.map((cluster) => {
              const isSelected = cluster.id === selectedClusterId;
              const aiScore = cluster.aiPriorityData?.score || 75;

              return (
                <div
                  key={cluster.id}
                  onClick={() => setSelectedClusterId(cluster.id)}
                  className={`p-4 rounded-lg border text-left cursor-pointer transition space-y-2 ${
                    isSelected
                      ? 'border-amber-500 bg-amber-50/40 shadow-sm'
                      : 'border-slate-200 bg-white hover:border-slate-300 hover:bg-slate-50'
                  }`}
                >
                  <div className="flex items-center justify-between gap-1 text-[11px]">
                    <span className="font-mono font-bold px-1.5 py-0.5 rounded bg-slate-900 text-white text-[10px]">
                      {cluster.id}
                    </span>
                    <span className={`px-2 py-0.5 rounded font-semibold text-[10px] ${
                      cluster.status === 'Escalation' ? 'bg-rose-100 text-rose-800' :
                      cluster.status === 'Ready' ? 'bg-amber-100 text-amber-900' :
                      cluster.status === 'Resolved' ? 'bg-emerald-100 text-emerald-900' :
                      'bg-slate-100 text-slate-700'
                    }`}>
                      {cluster.status}
                    </span>
                  </div>

                  <div className="font-bold text-xs text-slate-900 leading-snug">
                    {cluster.title}
                  </div>

                  <div className="text-[11px] text-slate-500 flex items-center gap-1 truncate">
                    <MapPin className="w-3 h-3 text-slate-400 shrink-0" />
                    <span className="truncate">{cluster.location}</span>
                  </div>

                  <div className="pt-2 border-t border-slate-100/80 flex items-center justify-between text-[11px]">
                    <span className="text-rose-700 font-bold">
                      AI Priority: {aiScore}/100
                    </span>
                    <span className="text-slate-500">
                      {cluster.reportsCount} reports • {cluster.evidenceCount} files
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        {/* Right Column: Grievance Generation & Resolution Console (8 cols) */}
        <div className="lg:col-span-8 space-y-6">
          {selectedCluster && (
            <>
              {/* Cluster Detail Header */}
              <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm space-y-4">
                <div className="flex flex-wrap items-start justify-between gap-3 pb-3 border-b border-slate-100">
                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <span className="font-mono text-xs font-bold px-2 py-0.5 rounded bg-slate-900 text-white">
                        {selectedCluster.id}
                      </span>
                      <span className="text-xs font-semibold text-slate-700 bg-slate-100 px-2 py-0.5 rounded">
                        {selectedCluster.category}
                      </span>
                      <TrustBadge type="ANALYSIS" size="xs" />
                    </div>
                    <h2 className="text-lg font-bold text-slate-900">
                      {selectedCluster.title}
                    </h2>
                    <div className="text-xs text-slate-500 mt-1 flex items-center gap-1.5">
                      <Building2 className="w-3.5 h-3.5 text-slate-400" />
                      <span>{selectedCluster.department}</span>
                    </div>
                  </div>

                  {/* Status Controller */}
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-semibold text-slate-600">Status:</span>
                    <select
                      value={selectedCluster.status}
                      onChange={(e) => handleStatusChange(e.target.value)}
                      className="text-xs font-semibold p-1.5 rounded border border-slate-300 bg-white"
                    >
                      <option value="Ready">Ready</option>
                      <option value="Escalation">Escalation</option>
                      <option value="Monitoring">Monitoring</option>
                      <option value="Resolved">Resolved</option>
                      <option value="Active">Active</option>
                    </select>
                  </div>
                </div>

                {/* Score Summary */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center text-xs">
                  <div className="bg-slate-50 p-2.5 rounded border border-slate-100">
                    <div className="text-[10px] uppercase font-semibold text-slate-400">Reports</div>
                    <div className="text-base font-bold text-slate-900 mt-0.5">{selectedCluster.reportsCount}</div>
                  </div>
                  <div className="bg-slate-50 p-2.5 rounded border border-slate-100">
                    <div className="text-[10px] uppercase font-semibold text-slate-400">Public Support</div>
                    <div className="text-base font-bold text-blue-800 mt-0.5">{selectedCluster.publicSupportScore}/100</div>
                  </div>
                  <div className="bg-slate-50 p-2.5 rounded border border-slate-100">
                    <div className="text-[10px] uppercase font-semibold text-slate-400">AI Priority Score</div>
                    <div className="text-base font-bold text-rose-700 mt-0.5">{selectedCluster.aiPriorityData?.score || 84}/100</div>
                  </div>
                  <div className="bg-slate-50 p-2.5 rounded border border-slate-100">
                    <div className="text-[10px] uppercase font-semibold text-slate-400">Evidence Files</div>
                    <div className="text-base font-bold text-teal-800 mt-0.5">{selectedCluster.evidenceCount} files</div>
                  </div>
                </div>

                {/* Grievance Submission Status Badge */}
                <div className="p-3 bg-slate-50 rounded border border-slate-200 text-xs flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <span className="font-semibold text-slate-700">Official Submission Status: </span>
                    <strong className="text-amber-800">{selectedCluster.grievanceStatus || 'Prepared for Official Submission'}</strong>
                  </div>

                  <button
                    onClick={handleMarkSubmitted}
                    className="px-3 py-1 bg-amber-600 hover:bg-amber-700 text-white rounded text-xs font-semibold transition"
                  >
                    Mark as Manually Submitted
                  </button>
                </div>
              </div>

              {/* Collective Grievance Text Generator */}
              <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm space-y-4">
                <div className="flex flex-wrap items-center justify-between gap-2 pb-2 border-b border-slate-100">
                  <div className="flex items-center gap-2">
                    <FileText className="w-4 h-4 text-teal-700" />
                    <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900">
                      Generated Collective Grievance Petition
                    </h3>
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={handleCopyGrievance}
                      className="inline-flex items-center gap-1 px-3 py-1.5 rounded bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-semibold transition border border-slate-300"
                    >
                      <Copy className="w-3.5 h-3.5" />
                      <span>{copied ? 'Copied to Clipboard!' : 'Copy Text'}</span>
                    </button>

                    <button
                      onClick={handleDownloadGrievance}
                      className="inline-flex items-center gap-1 px-3 py-1.5 rounded bg-slate-900 hover:bg-slate-800 text-white text-xs font-semibold transition"
                    >
                      <Download className="w-3.5 h-3.5" />
                      <span>Download .txt</span>
                    </button>
                  </div>
                </div>

                <div className="relative">
                  <textarea
                    rows={12}
                    readOnly
                    value={grievanceContent}
                    className="w-full text-xs font-mono p-3.5 bg-slate-950 text-slate-200 rounded-lg leading-relaxed border border-slate-800 focus:outline-none select-all"
                  />
                </div>
              </div>

              {/* Official Response Recorder */}
              <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-sm space-y-3">
                <h3 className="text-xs font-bold uppercase tracking-wider text-slate-900 pb-2 border-b border-slate-100">
                  Log Official Agency Response
                </h3>

                {selectedCluster.officialResponse && (
                  <div className="p-3 bg-emerald-50 border border-emerald-200 rounded text-xs text-emerald-950 space-y-1">
                    <div className="font-bold flex items-center gap-1.5 text-emerald-900">
                      <CheckCircle className="w-4 h-4 text-emerald-600" />
                      Current Official Response Recorded:
                    </div>
                    <p className="font-sans text-emerald-800">{selectedCluster.officialResponse}</p>
                  </div>
                )}

                <form onSubmit={handleAddResponse} className="space-y-3">
                  <div>
                    <label className="block text-xs font-medium text-slate-700 mb-1">
                      Add / Update Official Action Taken
                    </label>
                    <textarea
                      rows={2}
                      value={officialResponseText}
                      onChange={(e) => setOfficialResponseText(e.target.value)}
                      placeholder="e.g. GCC Electrical division dispatched work order #4421 for inspection within 24 hours..."
                      className="w-full text-xs p-2.5 rounded border border-slate-300 focus:ring-1 focus:ring-slate-800"
                    />
                  </div>

                  <div className="flex items-center justify-between">
                    {responseSuccess && (
                      <span className="text-xs text-emerald-700 font-semibold">
                        Official response logged successfully.
                      </span>
                    )}
                    <button
                      type="submit"
                      disabled={!officialResponseText.trim()}
                      className="ml-auto inline-flex items-center gap-1.5 px-3.5 py-2 rounded bg-slate-900 hover:bg-slate-800 disabled:bg-slate-200 text-white text-xs font-semibold transition"
                    >
                      <Send className="w-3.5 h-3.5" />
                      <span>Record Response</span>
                    </button>
                  </div>
                </form>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
